import { Colors } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	safeArea: { flex: 1, backgroundColor: Colors.background },
	header: {
		height: 64,
		paddingHorizontal: 20,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	headerButton: {
		width: 36,
		height: 36,
		alignItems: "center",
		justifyContent: "center",
	},
	headerActions: { flexDirection: "row", alignItems: "center", gap: 8 },
	content: { paddingHorizontal: 26, paddingTop: 12, paddingBottom: 28 },
	title: {
		color: Colors.text,
		fontSize: 25,
		lineHeight: 32,
		fontWeight: "800",
	},
	categoryBadge: {
		alignSelf: "flex-start",
		marginTop: 12,
		paddingHorizontal: 13,
		height: 34,
		borderRadius: 11,
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		backgroundColor: Colors.surface,
	},
	categoryText: { color: Colors.text, fontSize: 13, fontWeight: "500" },
	dueRow: {
		marginTop: 24,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	dueDate: { flexDirection: "row", alignItems: "center", gap: 9 },
	dueText: { color: Colors.text, fontSize: 13, fontWeight: "600" },
	statusBadge: {
		minWidth: 54,
		height: 27,
		borderRadius: 14,
		alignItems: "center",
		justifyContent: "center",
		paddingHorizontal: 12,
		backgroundColor: Colors.accent,
	},
	statusText: { color: Colors.text, fontSize: 11, fontWeight: "700" },
	sectionTitle: {
		marginTop: 26,
		color: Colors.text,
		fontSize: 14,
		fontWeight: "800",
	},
	description: {
		marginTop: 10,
		color: Colors.text,
		fontSize: 14,
		lineHeight: 20,
	},
	metadataCard: {
		marginTop: 20,
		borderRadius: 13,
		borderWidth: StyleSheet.hairlineWidth,
		borderColor: Colors.border,
		backgroundColor: Colors.surface,
	},
	metadataRow: {
		height: 52,
		paddingHorizontal: 15,
		flexDirection: "row",
		alignItems: "center",
	},
	metadataLabel: {
		marginLeft: 10,
		color: Colors.text,
		fontSize: 11,
		fontWeight: "500",
	},
	metadataValueGroup: {
		marginLeft: "auto",
		flexDirection: "row",
		alignItems: "center",
		gap: 5,
	},
	metadataValue: { color: Colors.text, fontSize: 10, fontWeight: "500" },
	statusDot: {
		width: 7,
		height: 7,
		borderRadius: 4,
		backgroundColor: Colors.primary,
	},
	divider: {
		height: StyleSheet.hairlineWidth,
		marginHorizontal: 14,
		backgroundColor: Colors.border,
	},
	actionRow: {
		marginTop: 30,
		flexDirection: "row",
		gap: 12,
	},
	primaryAction: {
		flex: 1,
		height: 48,
		borderRadius: 11,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 10,
		backgroundColor: Colors.primary,
	},
	primaryActionText: {
		color: Colors.background,
		fontSize: 12,
		fontWeight: "700",
	},
	secondaryAction: {
		flex: 1,
		height: 48,
		borderRadius: 11,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 10,
		backgroundColor: Colors.surface,
	},
	secondaryActionText: { color: Colors.text, fontSize: 12, fontWeight: "700" },
	disabledAction: { opacity: 0.5 },
	pressed: { opacity: 0.82, transform: [{ scale: 0.99 }] },
});
