import { Colors } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	safeArea: { flex: 1, backgroundColor: Colors.background },
	header: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 24,
		paddingTop: 12,
		paddingBottom: 14,
	},
	title: {
		color: Colors.text,
		fontSize: 26,
		lineHeight: 32,
		fontWeight: "800",
	},
	headerActions: { flexDirection: "row", alignItems: "center", gap: 14 },
	offlineStatus: { flexDirection: "row", alignItems: "center", gap: 6 },
	onlineDot: {
		width: 9,
		height: 9,
		borderRadius: 5,
		backgroundColor: Colors.primary,
	},
	offlineText: { color: Colors.text, fontSize: 12, fontWeight: "600" },
	iconButton: {
		width: 32,
		height: 32,
		alignItems: "center",
		justifyContent: "center",
	},
	searchRow: { flexDirection: "row", paddingHorizontal: 18, gap: 10 },
	searchBox: {
		flex: 1,
		height: 48,
		borderRadius: 16,
		paddingHorizontal: 15,
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
		backgroundColor: Colors.surface,
	},
	searchInput: {
		flex: 1,
		height: "100%",
		paddingVertical: 0,
		color: Colors.text,
		fontSize: 14,
	},
	filterButton: {
		width: 48,
		height: 48,
		borderRadius: 16,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: Colors.surface,
	},
	categoryScroller: { flexGrow: 0, height: 60 },
	chipRow: { gap: 7, paddingHorizontal: 18, paddingVertical: 12 },
	statusRow: {
		minHeight: 54,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 18,
		borderBottomWidth: StyleSheet.hairlineWidth,
		borderBottomColor: Colors.border,
	},
	statusChips: { flexDirection: "row", gap: 7 },
	sortButton: {
		flexDirection: "row",
		alignItems: "center",
		gap: 4,
		paddingVertical: 10,
	},
	sortLabel: { color: Colors.text, fontSize: 12, fontWeight: "700" },
	taskListContent: {
		flexGrow: 1,
		paddingHorizontal: 18,
		paddingTop: 14,
		paddingBottom: 96,
	},
	emptyText: {
		color: Colors.icon,
		textAlign: "center",
		marginTop: 36,
		fontSize: 14,
	},
	fab: {
		position: "absolute",
		right: 22,
		bottom: 20,
		width: 58,
		height: 58,
		borderRadius: 29,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: Colors.primary,
		shadowColor: Colors.text,
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.22,
		shadowRadius: 7,
		elevation: 6,
	},
	fabPressed: { transform: [{ scale: 0.96 }], opacity: 0.9 },
});
